export const ADD_ITEM = 'ADD_ITEM'
export const GET_ITEMS = 'GET_ITEMS'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const SET_CURRENT_ITEM = 'GET_CURRENT_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'